### ISSUE TITLE
Citizen Recall

### ISSUE THREAD

**Issue by BoneyMC** [Minecolonies/minecolonies#240] opened 2016-10-29 16:02 UTC
### Minecolonies version

4.61
### Expected behavior

Town hall should recall citizens that are no employed.
### Actual behaviour

Doesn't do anything
### Steps to reproduce the problem

Go to a town hall and try to recall citizens

**Comment by Kostronor** [comment] 2016-11-01 16:12
duplicate of #66

**Closed by Kostronor** 2016-11-01 16:12 UTC
Labels: bug, help wanted
