### ISSUE TITLE
Citizens should walk faster on paths

### ISSUE THREAD

**Issue by nojo121** [Minecolonies/minecolonies#210] opened 2016-10-16 14:52 UTC
### Expected behavior

Citizens walk faster on specific blocks like:
-gravel
-stone bricks
-grass path block 
citizens prefer to walk on paths because it's faster
### Actual behaviour

normal (slow) walking speed regardless of which block they are walking on and weird pathfinding sometimes.
### Steps to reproduce the problem

just watch the citizens for example the builder when he's building something and needs materials.
Then he goes back to his hut. And then back to the cunstruction area.

**Comment by Kostronor** [comment] 2016-10-16 18:42
Somewhat duplicate of #20

**Comment by nojo121** [comment] 2016-10-16 19:11
nope it's not.
#20: automaticly build road/path
#210: citizens walk faster on these roads/paths

**Closed** 2016-12-08 15:41 UTC
Labels: ai, enhancement, path finding
